language: php
php:
    - "5.4"
    - "5.3"
    - "5.5"
    - "5.6"
    - "7.0"
    - "nightly"
    - hhvm
before_script:
  - composer install
script: vendor/bin/phpunit .
addons:
    code_climate:
        repo_token: a419419b65eb60ca8bd19f67a54416b21e7e759c5674594cc0996f4304c8e42d
sudo: false

